- name: Install and manage Nginx
  hosts: webserver
  become: yes

  tasks:
    - name: Install Nginx (Ubuntu/Debian)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
      notify: restart nginx
      tags: install

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      tags: start

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
