
- name: Handlers and Tags
  hosts: all
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify: restart nginx
      tags: install

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
      tags: start

    - name: Stop nginx service
      service:
        name: nginx
        state: stopped
      tags: stop

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

