- name: Ensure temporary clone directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ local_source_clone }}"
    - "{{ local_dest_clone }}"

- name: Copy source files to temporary clone
  copy:
    src: "{{ source_git_repo }}/"
    dest: "{{ local_source_clone }}/"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0755'
    remote_src: yes

- name: Clone destination Git repo to temporary directory
  git:
    repo: "{{ destination_git_repo }}"
    dest: "{{ local_dest_clone }}"
    version: main
    force: yes
    update: yes

- name: Copy files from source temp to destination temp
  copy:
    src: "{{ local_source_clone }}/"
    dest: "{{ local_dest_clone }}/"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0755'
    remote_src: yes

- name: Commit changes to destination repo
  command: >
    git add .
    && git commit -m "{{ commit_message }}"
  args:
    chdir: "{{ local_dest_clone }}"
  register: git_commit
  ignore_errors: yes


- name: Ensure temporary clone directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ local_source_clone }}"
    - "{{ local_dest_clone }}"

- name: Copy source files to temporary clone
  copy:
    src: "{{ source_git_repo }}/"
    dest: "{{ local_source_clone }}/"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0755'
    remote_src: yes

- name: Clone destination Git repo to temporary directory
  git:
    repo: "{{ destination_git_repo }}"
    dest: "{{ local_dest_clone }}"
    version: main
    force: yes
    update: yes

- name: Copy files from source temp to destination temp
  copy:
    src: "{{ local_source_clone }}/"
    dest: "{{ local_dest_clone }}/"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0755'
    remote_src: yes

- name: Commit changes to destination repo
  command: >
    git add .
    && git commit -m "{{ commit_message }}"
  args:
    chdir: "{{ local_dest_clone }}"
  register: git_commit
  ignore_errors: yes

- name: Push changes to remote Git repo
  command: git push origin main
  args:
    chdir: "{{ local_dest_clone }}"
  when: git_commit is succeeded
