 #java_project_path: /home/dinesh12/Desktop/asowmiya/sample2
 #jar_destination: /home/dinesh12/Videos/java_demo

java_project_path: "{{ survey_java_project_path | default('/home/dinesh12/Desktop/asowmiya/sample2') }}"
jar_destination: "{{ survey_jar_destination | default('/home/dinesh12/Videos/java_demo') }}"
# vars file for roles/java_app
